### ISSUE TITLE
.editor-wrapper .content-wrapper > div covers UI

### ISSUE THREAD

**Issue by flipswitchingmonkey** [Flamenco/grav-plugin-editor#2] opened 2018-05-02 16:10 UTC
.editor-wrapper .content-wrapper > div has a height setting of 100%

In my case (on both Firefox and Chrome) this causes the gm-scrollbar -horizontal div to cover the entire page and prevent any interaction.

Disabling 
.editor-wrapper .content-wrapper > div {
    height: 100% !important;
}
makes it work again (albeit without a working horizontal scrollbar, of course...)

**Comment by Flamenco** [comment] 2018-05-02 18:39
Yes, It is set to important for me.  Is this the div in question (see screenshot)...
<img width="941" alt="screen shot 2018-05-02 at 2 38 58 pm" src="https://user-images.githubusercontent.com/819940/39542476-af151320-4e16-11e8-94e3-26fd2285c72b.png">

**Comment by Flamenco** [comment] 2018-05-02 18:51
@flipswitchingmonkey When you say 'prevent any action', do you mean not scrolling, or you that you can't access the menu buttons.  I can't reproduce this either on Chrome or Firefox.

**Comment by Flamenco** [comment] 2018-05-02 18:53
Also, gm-scrollbar-horizontal is not present for me.  Do you know what is pulling that in?

**Comment by flipswitchingmonkey** [comment] 2018-05-03 11:26
Seems like it is coming in from the default Admin theme:
![image](https://user-images.githubusercontent.com/6930367/39573906-66e248e2-4ed5-11e8-90af-5425dada018d.png)

What happens is that this element lies on top of everything else:
![image](https://user-images.githubusercontent.com/6930367/39573947-8d96189c-4ed5-11e8-8f62-9df5ce8eaf66.png)
so no interaction with the underlying elements is possible.

Edit: For the time being, removing the !important from the .content-wrapper > div works for me.

**Comment by Flamenco** [comment] 2018-05-03 17:14
Got it.  This only shows up on touch-devices (iphone/android).

**Comment by Flamenco** [comment] 2018-05-03 17:23
If you set the gm-scrollbar z-index to -1, does that fix it?  
Or try the .editor-wrapper .content-wrapper div to z-index 2 or 3

**Comment by Flamenco** [comment] 2018-05-03 17:31
gm- stuff comes from gemini-scrollbar.  I don't think we need this.
Can you also try putting gm-prevented class in the same element as the editor-wrapper element class?

**Comment by paulmassen** [comment] 2018-05-12 09:13
I have the same problem too.
To me, it seems like this line: https://github.com/Flamenco/grav-plugin-editor/blob/master/assets/editor.scss#L53
overrides this https://github.com/getgrav/grav-plugin-admin/blob/develop/themes/grav/scss/template/modules/_scrollbars.scss#L48

Thus, instead of being 6px high, it is set to 100% height.

**Comment by Flamenco** [comment] 2018-05-12 10:51
@paulmassen What device/browser are you using?

**Comment by paulmassen** [comment] 2018-05-14 07:37
Tested on chrome on multiple computer. I think this did not appear on mobile, TBC.

**Comment by Flamenco** [comment] 2018-05-14 16:17
I can't get the gemini toolbar to show up on any of my devices (IOS, OSX), so it's making it hard to test.  I might have access to a windows PC later today and will get to the bottom of this.

**Comment by moremeatlessfat** [comment] 2018-05-21 07:06
Agree, I'm getting the same issue in Chrome on a Windows machine.  I just disable the height: 100% for the scrollbar, and I am able to click on the links.

**Comment by Flamenco** [comment] 2018-05-21 12:51
OK, I found the problem.  It's only on Windows environments, regardless of the browser.   Will fix today.  Thanks everyone for the feedback.

**Comment by Flamenco** [comment] 2018-05-21 13:26
I am disabling gm-scrollbar and that seems to work.
```css
.editor-wrapper .gm-scrollbar {
   display:none
}
```

**Comment by Flamenco** [comment] 2018-05-21 13:40
Fixed in https://github.com/Flamenco/grav-plugin-editor/releases/tag/0.1.5
Also fixed 100% height issue when editing.  Please confirm this solves your issue.

**Closed as completed by Flamenco** 2018-05-21 13:40 UTC
Labels: bug
